### ISSUE TITLE
[Documentation] Explain how to figure out AWS remote URL

### ISSUE THREAD

**Issue by Jubijub** [yvele/poosh#3]
The documentation contains this : 

```
  plugins : ["s3"],
  baseDir : "./deploy",
  remote  : "s3-us-west-2.amazonaws.com/my-bucket",
```

It's not immediately obvious what to put as a remote, considering that S3 URLs are different : 
Endpoint: trololo.ch.s3-website.eu-central-1.amazonaws.com
- The endpointURL is not suitable
- Using s3-website.eu-central-1.amazonaws.com/trololo.ch  isn't either
- s3-eu-central-1.amazonaws.com/trololo.ch is the right one (ie without the 'website.' part

It's dictacted by AWS and is outside of the scope of your project, but as AWS noobs (like me) may use your project for convenience, it probably doesn't hurt to clarify how to get the right URL (I use S3 "static website" feature)

**Comment by yvele** [comment]
S3 endpoint are pretty straightforward: http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region
But I still added a link to AWS S3 endpoint doc: https://github.com/yvele/poosh/commit/434c1a6e92a21fd0142dc325a46713959c415e95
