### ISSUE TITLE
README on NPM does not match latest version

### ISSUE THREAD

**Issue by yvele** [yvele/poosh#4]
When using [Lerna](https://github.com/lerna) to publish NPM packages, REAMDE file is not updated.
Lerna Issue: https://github.com/lerna/lerna/issues/64
Related to NPM issue: ~~https://github.com/npm/newww/issues/389~~ https://github.com/npm/registry/issues/42

**Comment by hzoo** [comment]
Fixed!! https://github.com/lerna/lerna/issues/64 😍

**Comment by yvele** [comment]
Thanks for the great news @hzoo :v:
