### ISSUE TITLE
Should I commit .poosh.cache to revision control?

### ISSUE THREAD

**Issue by ubershmekel** [yvele/poosh#9]
I think I shouldn't, but it would be nice to have an official answer in the readme.

**Comment by yvele** [comment]
I think you should commit `.poosh.cache` manually in your SCM if you are not using [continuous integration](https://en.wikipedia.org/wiki/Continuous_integration) to deploy.

I also think that if you are working with many people and some of them are deploying, then you should use a proper [CI](https://en.wikipedia.org/wiki/Continuous_integration) deployment

But it's up to the developer, I cannot know all possible scenarios
